### ISSUE TITLE
strategy_config 下面的配置能提供以一下吗？

### ISSUE THREAD

**Issue by yyun** [Bohr1005/smartquant#2]
strategy_config 没有内容 ，程序跑不起来

**Comment by Bohr1005** [comment]
config_读取的参数就是strategy_config里面配置的，这是一个实盘的策略，具体参数我删掉了，可以自己配置这里面的参数:long_thres,short_thres,window,vol,profit_target,pending_dist,exit_dist,wait,use_close_offset,tick_size。这个策略交易的是股指，但是会用到股票现货合成的指数行情(对应策略里的变量spot_,他的行情来自L2Gateway这个类接受的端口转发，这个你没发用，能用的接口只有CtpGateway)。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 上午10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Bohr1005/smartquant] strategy_config 下面的配置能提供以一下吗？ (Issue #2)





 
strategy_config 没有内容 ，程序跑不起来
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yyun** [comment]
> 好的，多谢
